name: 'jaffle_shop'
version: '1.0.0'
config-version: 2

profile: 'jaffle_shop'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seed"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"


# Tags accumulate hierarchically
models:
  jaffle_shop:
    stage:
      +materialized: view
      jaffle_shop:
        +tags: "jaffle"
      stripe:
        +tags: "stripe"
    marts:
      +materialized: table

seeds:
  jaffle_shop:
      +tags: "jaffle"
